coverage:
  status:
    project:
      default:
        # Commits pushed to main should not make the overall
        # project coverage decrease by more than 1%
        target: auto
        threshold: 1%
    patch:
      default:
        # Be tolerant on code coverage diff on PRs to limit
        # noisy red coverage status on github PRs.
        target: auto
        threshold: 20%
