"""PowerShell completion script generator.

Unlike the bash/zsh/fish scripts, the PowerShell script carries no static data:
every TAB runs ``<prog> __complete`` in *full* mode (see :meth:`.App._run_complete`),
and the engine supplies command names, option names, choices, and completer values.
The script only splits the command line into words, quotes the returned
candidates for PowerShell, and adds path completions when asked to.

Works in PowerShell 7+ (``pwsh``) and Windows PowerShell 5.1 (``powershell.exe``),
so it avoids newer syntax (``??``, ternaries) and stays ASCII (5.1 reads a
BOM-less script as ANSI).
"""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from cyclopts import App

_TEMPLATE = r"""# PowerShell completion for __PROG_COMMENT__ (generated by cyclopts).
Register-ArgumentCompleter -Native -CommandName __COMMAND_NAMES__ -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $separator = [char]0x1f
    $words = New-Object System.Collections.Generic.List[string]
    $current = ''
    $elements = $commandAst.CommandElements
    for ($i = 1; $i -lt $elements.Count; $i++) {
        $element = $elements[$i]
        $extent = $element.Extent
        if ($extent.StartOffset -ge $cursorPosition) { break }
        $isString = $element -is [System.Management.Automation.Language.StringConstantExpressionAst]
        if ($extent.EndOffset -lt $cursorPosition) {
            if ($isString) { $words.Add($element.Value) } else { $words.Add($extent.Text) }
        } elseif ($isString -and $extent.EndOffset -eq $cursorPosition) {
            $current = $element.Value
        } else {
            $current = $extent.Text.Substring(0, $cursorPosition - $extent.StartOffset).Trim("'", '"')
        }
    }
    $words.Add($current)

    $quote = ''
    if ($wordToComplete.StartsWith("'") -or $wordToComplete.StartsWith('"')) { $quote = $wordToComplete.Substring(0, 1) }

    $savedWords = $env:CYCLOPTS_COMPLETE_WORDS
    $savedEncoding = $env:PYTHONIOENCODING
    $savedConsoleEncoding = $null
    try {
        $env:CYCLOPTS_COMPLETE_WORDS = -join ($words | ForEach-Object { $_ + $separator })
        $env:PYTHONIOENCODING = 'utf-8'
        try {
            $savedConsoleEncoding = [Console]::OutputEncoding
            [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding $false
        } catch { }
        $lines = & __PROG_INVOKE__ __complete 2>$null
    } finally {
        $env:CYCLOPTS_COMPLETE_WORDS = $savedWords
        $env:PYTHONIOENCODING = $savedEncoding
        if ($null -ne $savedConsoleEncoding) {
            try { [Console]::OutputEncoding = $savedConsoleEncoding } catch { }
        }
    }

    $started = $false
    $prefix = ''
    $files = $false
    foreach ($line in $lines) {
        $line = "$line".TrimEnd("`r")
        if (-not $started) {
            $started = $line -eq ($separator + 'begin')
            continue
        }
        $fields = $line.Split("`t")
        if ($line.StartsWith($separator)) {
            if ($fields[0] -eq ($separator + 'prefix') -and $fields.Count -gt 1) { $prefix = $fields[1] }
            elseif ($fields[0] -eq ($separator + 'files')) { $files = $true }
            continue
        }
        $value = $fields[0]
        if (-not $value) { continue }
        $description = $value
        if ($fields.Count -gt 1 -and $fields[1]) { $description = $fields[1] }
        $resultType = 'ParameterValue'
        if ($value.StartsWith('-') -and -not $prefix) { $resultType = 'ParameterName' }
        $text = $prefix + $value
        if ($quote -eq '"') {
            $text = '"' + ($text -replace '([`"$])', '`$1') + '"'
        } elseif ($quote -eq "'" -or $text -match '[\s''"`$,;(){}@|&<>#]') {
            $text = "'" + $text.Replace("'", "''") + "'"
        }
        New-Object System.Management.Automation.CompletionResult $text, $value, $resultType, $description
    }

    if ($files) {
        $pathWord = $wordToComplete
        if ($prefix -and $pathWord.StartsWith($prefix)) { $pathWord = $pathWord.Substring($prefix.Length) }
        foreach ($path in [System.Management.Automation.CompletionCompleters]::CompleteFilename($pathWord)) {
            New-Object System.Management.Automation.CompletionResult ($prefix + $path.CompletionText), $path.ListItemText, $path.ResultType, $path.ToolTip
        }
    }
}
"""


def _single_quote(text: str) -> str:
    return "'" + text.replace("'", "''") + "'"


def generate_completion_script(app: "App", prog_name: str) -> str:
    """Generate a PowerShell completion script.

    Parameters
    ----------
    app : App
        The Cyclopts application (unused; the script asks the program at TAB time).
    prog_name : str
        Program name; also registered as ``<prog_name>.exe`` for Windows.

    Returns
    -------
    str
        PowerShell script registering a native argument completer.
    """
    names = [prog_name] if prog_name.lower().endswith(".exe") else [prog_name, f"{prog_name}.exe"]
    return (
        _TEMPLATE.replace("__PROG_COMMENT__", prog_name.replace("\r", " ").replace("\n", " "))
        .replace("__COMMAND_NAMES__", ", ".join(_single_quote(name) for name in names))
        .replace("__PROG_INVOKE__", _single_quote(prog_name))
    )
