"""PowerShell completion script generator.

Like the bash/zsh/fish scripts, the PowerShell script carries the app's commands,
options, and static choices, and completes them without starting Python. The
data is emitted as nested hashtables walked by one fixed routine; only a
parameter with a :attr:`.Parameter.completer` runs ``<prog> __complete`` (in
*full* mode, see :meth:`.App._run_complete`), which also handles that slot's
``=`` prefix and multi-value position.

Works in PowerShell 7+ (``pwsh``) and Windows PowerShell 5.1 (``powershell.exe``),
so it avoids newer syntax (``??``, ternaries) and stays ASCII (5.1 reads a
BOM-less script as ANSI).
"""

from typing import TYPE_CHECKING

from cyclopts.completion._base import (
    CompletionAction,
    CompletionData,
    app_description,
    clean_choice_text,
    extract_completion_data,
    get_completion_action,
    strip_markup,
)

if TYPE_CHECKING:
    from cyclopts import App
    from cyclopts.argument import Argument

_TEMPLATE = r"""# PowerShell completion for __PROG_COMMENT__ (generated by cyclopts).
& {
__NODES__
$tree = __ROOT__
$programName = __PROG_INVOKE__
$endOfOptions = __END_OF_OPTIONS__

Register-ArgumentCompleter -Native -CommandName __COMMAND_NAMES__ -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $separator = [char]0x1f
    $words = New-Object System.Collections.Generic.List[string]
    $current = ''
    $elements = $commandAst.CommandElements
    for ($i = 1; $i -lt $elements.Count; $i++) {
        $element = $elements[$i]
        $extent = $element.Extent
        if ($extent.StartOffset -ge $cursorPosition) { break }
        $isString = $element -is [System.Management.Automation.Language.StringConstantExpressionAst]
        if ($extent.EndOffset -lt $cursorPosition) {
            if ($isString) { $words.Add($element.Value) } else { $words.Add($extent.Text) }
        } elseif ($isString -and $extent.EndOffset -eq $cursorPosition) {
            $current = $element.Value
        } else {
            $current = $extent.Text.Substring(0, $cursorPosition - $extent.StartOffset).Trim("'", '"')
        }
    }

    $quote = ''
    if ($wordToComplete.StartsWith("'") -or $wordToComplete.StartsWith('"')) { $quote = $wordToComplete.Substring(0, 1) }

    $format = {
        param($text)
        if ($quote -eq '"') { return '"' + ($text -replace '([`"$\u201C-\u201E])', '`$1') + '"' }
        if ($quote -eq "'" -or $text -match '[\s''"`$,;(){}@|&<>#*?\[\u2018-\u201E]') {
            return "'" + ($text -replace '([''\u2018-\u201B])', '$1$1') + "'"
        }
        $text
    }

    # Option and command names are case-sensitive, so match them with -ceq.
    $findOption = {
        param($node, $name)
        foreach ($option in $node.O) { foreach ($n in $option.N) { if ($n -ceq $name) { return $option } } }
    }

    # An option-like word ends an option's values; a negative number does not.
    $isOption = { param($word) $word.Length -gt 1 -and $word.StartsWith('-') -and $word -notmatch '^-\.?\d' }

    # Walk the words before the cursor: descend into commands, skip option values,
    # count positionals, and note an option whose values are still being typed.
    $node = $tree
    $position = 0
    $afterDelimiter = $false
    $valueOption = $null
    $i = 0
    while ($i -lt $words.Count) {
        $word = $words[$i]
        $i++
        if (-not $afterDelimiter -and $endOfOptions -and $word -ceq $endOfOptions) { $afterDelimiter = $true; continue }
        if (-not $afterDelimiter -and (& $isOption $word)) {
            if ($word.Contains('=')) { continue }
            $option = & $findOption $node $word
            if (-not $option -or $option.A -eq 0) { continue }
            $taken = 0
            while ($i -lt $words.Count -and ($option.A -lt 0 -or $taken -lt $option.A) -and -not (& $isOption $words[$i])) {
                $i++
                $taken++
            }
            if ($i -ge $words.Count -and ($option.A -lt 0 -or $taken -lt $option.A)) { $valueOption = $option }
            continue
        }
        if ($position -eq 0) {
            $child = $null
            foreach ($command in $node.C) { if ($command.N -ceq $word) { $child = $command.T; break } }
            if ($child) { $node = $child; continue }
        }
        $position++
    }

    $prefix = ''
    $incomplete = $current
    $slot = $null
    $listOptions = $false
    $listCommands = $false
    if ($valueOption -and -not (& $isOption $current)) {
        $slot = $valueOption.V
    } elseif (-not $afterDelimiter -and $current.StartsWith('-')) {
        $equals = $current.IndexOf('=')
        if ($equals -ge 0) {
            $option = & $findOption $node $current.Substring(0, $equals)
            if ($option -and $option.A -ne 0) {
                $prefix = $current.Substring(0, $equals + 1)
                $incomplete = $current.Substring($equals + 1)
                $slot = $option.V
            }
        } else {
            $listOptions = $true
        }
    } else {
        $listCommands = $position -eq 0
        if ($position -lt $node.P.Count) { $slot = $node.P[$position] } elseif ($node.R) { $slot = $node.R }
    }

    $seen = New-Object 'System.Collections.Generic.HashSet[string]'
    $emit = {
        param($value, $description, $resultType)
        if (-not $value -or -not $value.StartsWith($incomplete, [StringComparison]::OrdinalIgnoreCase)) { return }
        if (-not $seen.Add($value)) { return }
        if (-not $description) { $description = $value }
        New-Object System.Management.Automation.CompletionResult (& $format ($prefix + $value)), $value, $resultType, $description
    }

    $files = ''
    if ($slot -and $slot.X) {
        # Completer-backed: ask the program, which returns every candidate for this slot.
        $words.Add($current)
        $program = $programName
        if ($elements[0] -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
            $resolved = Get-Command -Name $elements[0].Value -CommandType Application -ErrorAction Ignore | Select-Object -First 1
            if ($resolved) { $program = $resolved.Source }
        }
        $savedWords = $env:CYCLOPTS_COMPLETE_WORDS
        $savedEncoding = $env:PYTHONIOENCODING
        $savedConsoleEncoding = $null
        try {
            $env:CYCLOPTS_COMPLETE_WORDS = -join ($words | ForEach-Object { $_ + $separator })
            $env:PYTHONIOENCODING = 'utf-8'
            try {
                $savedConsoleEncoding = [Console]::OutputEncoding
                [Console]::OutputEncoding = New-Object System.Text.UTF8Encoding $false
            } catch { }
            $lines = & $program __complete 2>$null
        } finally {
            $env:CYCLOPTS_COMPLETE_WORDS = $savedWords
            $env:PYTHONIOENCODING = $savedEncoding
            if ($null -ne $savedConsoleEncoding) {
                try { [Console]::OutputEncoding = $savedConsoleEncoding } catch { }
            }
        }
        $prefix = ''
        $incomplete = ''
        $started = $false
        foreach ($line in $lines) {
            $line = "$line".TrimEnd("`r")
            if (-not $started) {
                $started = $line -ceq ($separator + 'begin')
                continue
            }
            $fields = $line.Split("`t")
            if ($line.StartsWith($separator)) {
                if ($fields[0] -ceq ($separator + 'prefix') -and $fields.Count -gt 1) { $prefix = $fields[1] }
                elseif ($fields[0] -ceq ($separator + 'files')) { $files = 'files' }
                continue
            }
            $resultType = 'ParameterValue'
            if ($fields[0].StartsWith('-') -and -not $prefix) { $resultType = 'ParameterName' }
            $description = ''
            if ($fields.Count -gt 1) { $description = $fields[1] }
            & $emit $fields[0] $description $resultType
        }
    } else {
        if ($listOptions) {
            foreach ($option in $node.O) { foreach ($n in $option.N) { & $emit $n $option.D 'ParameterName' } }
        }
        if ($listCommands) {
            foreach ($command in $node.C) { & $emit $command.N $command.D 'ParameterValue' }
        }
        if ($slot) {
            foreach ($choice in $slot.C) { & $emit $choice '' 'ParameterValue' }
            $files = $slot.F
        }
    }

    if ($files) {
        $pathWord = $wordToComplete
        if ($prefix -and $pathWord.StartsWith($prefix)) { $pathWord = $pathWord.Substring($prefix.Length) }
        foreach ($path in [System.Management.Automation.CompletionCompleters]::CompleteFilename($pathWord)) {
            if ($files -eq 'dirs' -and $path.ResultType -ne 'ProviderContainer') { continue }
            # CompleteFilename quotes and wildcard-escapes for cmdlets (5.1 leaves backticks bare); recover the literal path.
            $raw = $path.CompletionText
            if ($raw.Length -gt 1 -and $raw.StartsWith("'") -and $raw.EndsWith("'")) {
                $raw = $raw.Substring(1, $raw.Length - 2) -replace '([''\u2018-\u201B])[''\u2018-\u201B]', '$1'
            }
            $raw = $raw -replace '`([\[\]`])', '$1'
            New-Object System.Management.Automation.CompletionResult (& $format ($prefix + $raw)), $path.ListItemText, $path.ResultType, $path.ToolTip
        }
    }
}.GetNewClosure()
}
"""

_ACTIONS = {CompletionAction.FILES: "files", CompletionAction.DIRECTORIES: "dirs"}


def _ps_string(text: str) -> str:
    """PowerShell string expression for ``text``; non-ASCII becomes char codes so the script stays ASCII."""
    if text.isascii():
        return "'" + text.replace("'", "''") + "'"
    units = text.encode("utf-16-le")
    codes = ",".join(f"0x{int.from_bytes(units[i : i + 2], 'little'):x}" for i in range(0, len(units), 2))
    return f"(-join [char[]]({codes}))"


def _ps_array(items: "list[str]") -> str:
    return "@(" + ", ".join(items) + ")"


def _value_entry(argument: "Argument") -> str:
    """``@{ C = choices; F = 'files'|'dirs'|''; X = has-completer }`` for an option value or positional slot."""
    choices = [clean_choice_text(c) for c in argument.get_choices(force=True) or ()]
    action = _ACTIONS.get(get_completion_action(argument.hint), "")
    completer = "$true" if argument.parameter.completer is not None else "$false"
    return f"@{{ C = {_ps_array([_ps_string(c) for c in choices if c])}; F = '{action}'; X = {completer} }}"


def _value_count(argument: "Argument") -> int:
    """Words an option consumes after its name; ``-1`` consumes until the next option-like word."""
    if argument.is_flag():
        return 0
    count, consume_all = argument.token_count()
    if consume_all and argument.parameter.consume_multiple:
        return -1
    return max(count, 1)


def _option_entry(names: "list[str]", description: str, value_count: int, value: str = "$null") -> str:
    return (
        f"@{{ N = {_ps_array([_ps_string(n) for n in names])}; D = {_ps_string(description)}; "
        f"A = {value_count}; V = {value} }}"
    )


def _node_body(
    data: CompletionData,
    child_nodes: "dict[str, str]",
    root_flag_descriptions: "dict[str, str]",
) -> str:
    """The ``@{ C = commands; O = options; P = positionals; R = rest }`` hashtable for one command path."""
    fmt = data.help_format

    options = []
    for argument in data.arguments:
        if not argument.show or argument.is_positional_only():
            continue
        description = strip_markup(argument.parameter.help or "", format=fmt)
        names = [n for n in argument.parameter.name or () if n.startswith("-")]
        if names:
            count = _value_count(argument)
            value = _value_entry(argument) if count else "$null"
            options.append(_option_entry(names, description, count, value))
        negatives = [n for n in argument.negatives if n.startswith("-")]
        if negatives:
            options.append(_option_entry(negatives, description, 0))

    flag_names: set[str] = set()
    for registered_command in data.commands:
        names = [n for n in registered_command.names if n.startswith("-")]
        if names:
            flag_names.update(names)
            options.append(_option_entry(names, app_description(registered_command.app, fmt), 0))
    for flag in (*data.help_flags, *data.version_flags):
        if flag.startswith("-") and flag not in flag_names:
            flag_names.add(flag)
            options.append(_option_entry([flag], root_flag_descriptions.get(flag, ""), 0))

    commands = [
        f"@{{ N = {_ps_string(name)}; D = {_ps_string(app_description(registered_command.app, fmt))}; "
        f"T = {child_nodes[name]} }}"
        for registered_command in data.commands
        for name in registered_command.names
        if not name.startswith("-") and name in child_nodes
    ]

    # Inherited (ancestor-meta) positionals were consumed before this path's
    # command name, so they never claim a slot here (same rule as bash).
    positionals = sorted(
        (a for a in data.launcher_arguments + data.own_arguments if a.index is not None and a.show),
        key=lambda a: a.index or 0,
    )
    # An iterable positional (``list[X]``, ``*args``) answers every later position.
    rest_index = next((i for i, a in enumerate(positionals) if a.is_var_positional()), None)
    if rest_index is None:
        rest_index = next((i for i, a in enumerate(positionals) if a.token_count()[1]), None)
    head = positionals if rest_index is None else positionals[:rest_index]
    rest = "$null" if rest_index is None else _value_entry(positionals[rest_index])

    return (
        "@{\n"
        f"    C = {_ps_array(commands)}\n"
        f"    O = {_ps_array(options)}\n"
        f"    P = {_ps_array([_value_entry(a) for a in head])}\n"
        f"    R = {rest}\n"
        "}"
    )


def generate_completion_script(app: "App", prog_name: str) -> str:
    """Generate a PowerShell completion script.

    Parameters
    ----------
    app : App
        The Cyclopts application to generate completion for.
    prog_name : str
        Program name; also registered as ``<prog_name>.exe`` for Windows.

    Returns
    -------
    str
        PowerShell script registering a native argument completer.
    """
    completion_data = extract_completion_data(app)
    root_data = completion_data[()]
    root_flag_descriptions = {
        name: app_description(rc.app, root_data.help_format)
        for rc in root_data.commands
        for name in rc.names
        if name.startswith("-")
    }

    # Emit each distinct node once, children first; aliases share a variable.
    statements: list[str] = []
    variables: dict[str, str] = {}

    def emit(path: tuple[str, ...]) -> str:
        data = completion_data[path]
        child_nodes = {}
        for registered_command in data.commands:
            for name in registered_command.names:
                if not name.startswith("-") and path + (name,) in completion_data:
                    child_nodes[name] = emit(path + (name,))
        body = _node_body(data, child_nodes, root_flag_descriptions)
        if body not in variables:
            variables[body] = f"$n{len(variables)}"
            statements.append(f"{variables[body]} = {body}")
        return variables[body]

    root = emit(())
    end_of_options = app.app_stack.resolve("end_of_options_delimiter", fallback="--")
    names = [prog_name] if prog_name.lower().endswith(".exe") else [prog_name, f"{prog_name}.exe"]
    return (
        _TEMPLATE.replace("__NODES__", "\n".join(statements))
        .replace("__ROOT__", root)
        .replace(
            "__PROG_COMMENT__",
            prog_name.replace("\r", " ").replace("\n", " ").encode("ascii", "backslashreplace").decode(),
        )
        .replace("__COMMAND_NAMES__", ", ".join(_ps_string(name) for name in names))
        .replace("__PROG_INVOKE__", _ps_string(prog_name))
        .replace("__END_OF_OPTIONS__", _ps_string(end_of_options) if end_of_options else "''")
    )
