name: Build package and push to PyPi

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: pypi
      url: https://pypi.org/p/cyclopts
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Needed for hatch-vcs to get version from git tags
      - uses: astral-sh/setup-uv@v7
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@v1.14.0
        if: github.event_name != 'workflow_dispatch'
